auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Dongdong
url: http://charle-y.github.io
feed: /atom.xml
author_info: <a href="http://charle-y.github.io">Dongdong</a>
